import { ReactNode } from 'react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import {
  Briefcase,
  LayoutDashboard,
  FileText,
  Settings,
  LogOut,
  Kanban,
  PenLine,
  CalendarDays,
} from 'lucide-react'

const NAV_ITEMS = [
  { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/jobs', label: 'Jobs', icon: Briefcase },
  { to: '/tracker', label: 'Tracker', icon: Kanban },
  { to: '/calendar', label: 'Calendar', icon: CalendarDays },
  { to: '/cover-letter', label: 'Cover Letter', icon: PenLine },
  { to: '/resumes', label: 'Resume', icon: FileText },
  { to: '/onboarding/preferences', label: 'Preferences', icon: Settings },
] as const

export default function AppLayout({ children }: { children: ReactNode }) {
  const { user, signOut } = useAuth()
  const location = useLocation()

  const isActive = (path: string) => {
    if (path === '/dashboard') return location.pathname === '/dashboard'
    if (path === '/jobs') return location.pathname === '/jobs'
    if (path === '/tracker') return location.pathname === '/tracker'
    if (path === '/cover-letter') return location.pathname.startsWith('/cover-letter')
    if (path === '/resumes') return location.pathname.startsWith('/resume') || location.pathname.startsWith('/resumes') || location.pathname.startsWith('/profile/resume')
    if (path === '/onboarding/preferences') return location.pathname.startsWith('/onboarding')
    return false
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-40">
        <nav className="max-w-6xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-4">
<Link
  to="/dashboard"
  className="flex items-center gap-2 shrink-0 text-slate-900 hover:text-blue-600 transition"
>
  <Briefcase className="w-6 h-6 text-blue-600" />
  <div className="flex items-baseline">
    <span className="font-bold text-lg">JobMatch AI</span>
    <span className="ml-2 inline-block text-xs bg-slate-100 text-slate-600 px-2 py-0.5 rounded-full">
      Generated by AI • Prompted by humans • Get the Vibe
    </span> 
  </div>
</Link>

<div className="flex items-center gap-1 sm:gap-2">
  {NAV_ITEMS.map(({ to, label, icon: Icon }) => {
    const active = isActive(to)
    return (
      <NavLink
        key={to}
        to={to}
        className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium transition ${
          active
            ? 'bg-blue-50 text-blue-700'
            : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'
        }`}
      >
        <Icon className="w-4 h-4 shrink-0" />
        <span className="hidden sm:inline">{label}</span>
      </NavLink>
    )
  })}
</div>

          <div className="flex items-center gap-2 shrink-0">
            <span className="text-sm text-slate-500 truncate max-w-[140px] sm:max-w-[200px]" title={user?.email ?? ''}>
              {user?.email}
            </span>
            <button
              onClick={signOut}
              className="p-2 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition"
              title="Sign out"
            >
              <LogOut className="w-4 h-4" />
            </button>
          </div>
        </nav>
      </header>

      <main>{children}</main>
    </div>
  )
}
